import { S3Client, PutObjectCommand, GetObjectCommand, DeleteObjectCommand } from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';
import { config } from '../config/index.js';
import { logger } from './logger.js';

// ============================================
// AWS S3 Service
// ============================================

let s3Client: S3Client | null = null;

/**
 * Initialize S3 client
 */
export const getS3Client = (): S3Client | null => {
  if (!config.aws.accessKeyId || !config.aws.secretAccessKey || !config.aws.s3.bucket) {
    logger.warn('AWS S3 credentials not configured. Image uploads require S3 (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_S3_BUCKET).');
    return null;
  }

  if (!s3Client) {
    s3Client = new S3Client({
      region: config.aws.region,
      credentials: {
        accessKeyId: config.aws.accessKeyId,
        secretAccessKey: config.aws.secretAccessKey,
      },
      ...(config.aws.s3.endpoint && {
        endpoint: config.aws.s3.endpoint,
        forcePathStyle: true, // For S3-compatible services
      }),
    });
  }

  return s3Client;
};

/**
 * Upload file to S3
 */
export const uploadToS3 = async (
  buffer: Buffer,
  key: string,
  contentType: string
): Promise<string> => {
  const client = getS3Client();
  if (!client) {
    throw new Error('S3 client not initialized. Please configure AWS credentials.');
  }

  const bucket = config.aws.s3.bucket;
  if (!bucket) {
    throw new Error('S3 bucket not configured');
  }

  const command = new PutObjectCommand({
    Bucket: bucket,
    Key: key,
    Body: buffer,
    ContentType: contentType,
    // Note: ACL is deprecated in newer S3 buckets, use bucket policy instead
    // ACL: 'public-read', // Uncomment if your bucket supports ACLs
  });

  await client.send(command);

  return getPublicUrlForKey(key);
};

/**
 * Get the public URL for an S3 key (used after client uploads via presigned URL)
 */
export const getPublicUrlForKey = (key: string): string => {
  const bucket = config.aws.s3.bucket!;
  if (config.aws.s3.cdnUrl) {
    return `${config.aws.s3.cdnUrl}/${key}`;
  } else if (config.aws.s3.endpoint) {
    return `${config.aws.s3.endpoint}/${bucket}/${key}`;
  } else {
    return `https://${bucket}.s3.${config.aws.region}.amazonaws.com/${key}`;
  }
};

/**
 * Generate a presigned URL for direct client upload
 * Client can PUT the file to the returned URL
 * @param key - S3 object key (e.g. characters/abc123.jpg)
 * @param contentType - MIME type of the file
 * @param expiresIn - URL expiry in seconds (default 15 minutes)
 */
export const getPresignedUploadUrl = async (
  key: string,
  contentType: string,
  expiresIn: number = 900
): Promise<{ uploadUrl: string; publicUrl: string; viewUrl: string }> => {
  const client = getS3Client();
  if (!client) {
    throw new Error('S3 client not initialized. Please configure AWS credentials.');
  }

  const bucket = config.aws.s3.bucket;
  if (!bucket) {
    throw new Error('S3 bucket not configured');
  }

  const command = new PutObjectCommand({
    Bucket: bucket,
    Key: key,
    ContentType: contentType,
  });

  const uploadUrl = await getSignedUrl(client, command, { expiresIn });
  const publicUrl = getPublicUrlForKey(key);

  // For private buckets: also return a presigned view URL (valid for 1 hour)
  const viewUrl = await getPresignedGetUrl(key, 3600);

  return { uploadUrl, publicUrl, viewUrl };
};

/**
 * Generate a presigned URL for viewing/downloading from private S3 bucket
 * @param key - S3 object key
 * @param expiresIn - URL expiry in seconds (default 1 hour)
 */
export const getPresignedGetUrl = async (
  key: string,
  expiresIn: number = 3600
): Promise<string> => {
  const client = getS3Client();
  if (!client) {
    throw new Error('S3 client not initialized. Please configure AWS credentials.');
  }

  const bucket = config.aws.s3.bucket;
  if (!bucket) {
    throw new Error('S3 bucket not configured');
  }

  const command = new GetObjectCommand({
    Bucket: bucket,
    Key: key,
  });

  return getSignedUrl(client, command, { expiresIn });
};

/**
 * Convert an S3 URL to a presigned view URL (for private buckets)
 * Returns the original URL if it's not from our S3 (e.g. local /uploads/ or external)
 */
export const getPresignedViewUrl = async (
  url: string,
  expiresIn: number = 3600
): Promise<string> => {
  const key = extractS3KeyFromUrl(url);
  if (!key) return url; // Not our S3 URL, return as-is

  return getPresignedGetUrl(key, expiresIn);
};

/**
 * Extract S3 object key from a URL that was generated by our upload
 * Returns null for local storage URLs or if the URL doesn't match our S3 patterns
 */
export const extractS3KeyFromUrl = (url: string): string | null => {
  if (!url || typeof url !== 'string') return null;

  // Local storage URLs - don't delete from S3
  if (url.startsWith('/uploads/')) return null;

  try {
    const parsed = new URL(url);
    const pathname = parsed.pathname;
    if (!pathname || pathname === '/') return null;

    const bucket = config.aws.s3.bucket;

    // CDN URL: pathname is /key
    if (config.aws.s3.cdnUrl && url.startsWith(config.aws.s3.cdnUrl)) {
      const key = pathname.replace(/^\//, '');
      return key || null;
    }

    // Endpoint URL (path style): pathname is /bucket/key
    if (config.aws.s3.endpoint && bucket) {
      const prefix = `/${bucket}/`;
      if (pathname.startsWith(prefix)) {
        return pathname.slice(prefix.length) || null;
      }
    }

    // Standard S3 URL: pathname is /key, verify it's our bucket
    if (
      bucket &&
      url.includes('.s3.') &&
      url.includes('amazonaws.com') &&
      parsed.hostname.startsWith(bucket + '.')
    ) {
      return pathname.replace(/^\//, '') || null;
    }

    return null;
  } catch {
    return null;
  }
};

/**
 * Transform entity avatar/backgroundImg URLs to presigned URLs (for private buckets)
 * Works for character, lorebook, persona - any entity with avatar and/or backgroundImg
 * Returns entity unchanged if S3 is not configured
 */
export const transformEntityImageUrls = async <T>(entity: T): Promise<T> => {
  const client = getS3Client();
  if (!client) return entity;

  const result = { ...entity } as Record<string, unknown>;
  const avatar = result.avatar;
  const backgroundImg = result.backgroundImg;

  if (avatar && typeof avatar === 'object' && avatar !== null && 'url' in avatar && typeof avatar.url === 'string') {
    result.avatar = {
      ...avatar,
      url: await getPresignedViewUrl(avatar.url),
    };
  }
  if (
    backgroundImg &&
    typeof backgroundImg === 'object' &&
    backgroundImg !== null &&
    'url' in backgroundImg &&
    typeof backgroundImg.url === 'string'
  ) {
    result.backgroundImg = {
      ...backgroundImg,
      url: await getPresignedViewUrl(backgroundImg.url),
    };
  }

  return result as T;
};

/**
 * Transform array of entities - replace S3 URLs with presigned URLs
 */
export const transformEntitiesImageUrls = async <T>(entities: T[]): Promise<T[]> => {
  return Promise.all(entities.map((e) => transformEntityImageUrls(e)));
};

/** @deprecated Use transformEntityImageUrls */
export const transformCharacterImageUrls = transformEntityImageUrls;

/** @deprecated Use transformEntitiesImageUrls */
export const transformCharactersImageUrls = transformEntitiesImageUrls;

/**
 * Safely delete an S3 object if the URL points to our S3 bucket
 * No-op if URL is local or S3 is not configured
 */
export const deleteFromS3IfExists = async (url: string): Promise<void> => {
  const client = getS3Client();
  if (!client) return;

  const key = extractS3KeyFromUrl(url);
  if (!key) return;

  try {
    await deleteFromS3(key);
  } catch (error) {
    logger.warn({ err: error, key, url }, 'Failed to delete old S3 object during image replacement');
    // Don't throw - image replacement should succeed even if cleanup fails
  }
};

/**
 * Delete file from S3
 */
export const deleteFromS3 = async (key: string): Promise<void> => {
  const client = getS3Client();
  if (!client) {
    throw new Error('S3 client not initialized');
  }

  const bucket = config.aws.s3.bucket;
  if (!bucket) {
    throw new Error('S3 bucket not configured');
  }

  const command = new DeleteObjectCommand({
    Bucket: bucket,
    Key: key,
  });

  await client.send(command);
};

